### ISSUE TITLE
issue about limit

### ISSUE THREAD

**Issue by johnfelipe** [roshinip21/LinkedIn-JobPosting-Profile-Scraper#1]
$ python Linkedin_JobPostings_Profile_Scraper.py
    Found 0 job listings.
    Found 0 job listings.
    Found 0 job listings.
    Found 0 job listings.
    Found 0 job listings.
    Found 0 job listings.
    Found 0 job listings.
    Found 0 job listings.
    Found 0 job listings.
    Found 0 job listings.
    Found 60 job listings.
    Found 0 job listings.
    Found 0 job listings.
    Found 0 job listings.
    Found 0 job listings.
    Found 0 job listings.
    Found 60 job listings.
    Please complete any manual actions (like MFA) and press Enter when you're on the LinkedIn feed...
    Profile page did not load as expected. Continuing with limited information.
    Could not access contact info. Profile Email will not be available.
    Traceback (most recent call last):
      File "d:\Users\GAMEMAX\Documents\BLUETAB\2024\HACKATON\LinkedIn-JobPosting-Profile-Scraper\LinkedIn-JobPosting-Profile-Scraper-main\Linkedin_JobPostings_Profile_Scraper.py", line 198, in <module>
        main()
      File "d:\Users\GAMEMAX\Documents\BLUETAB\2024\HACKATON\LinkedIn-JobPosting-Profile-Scraper\LinkedIn-JobPosting-Profile-Scraper-main\Linkedin_JobPostings_Profile_Scraper.py", line 195, in main
        send_email(sender_email, sender_password, recipient_emails, subject, body, jobs_df, profile_df)
      File "d:\Users\GAMEMAX\Documents\BLUETAB\2024\HACKATON\LinkedIn-JobPosting-Profile-Scraper\LinkedIn-JobPosting-Profile-Scraper-main\Linkedin_JobPostings_Profile_Scraper.py", line 167, in send_email
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\GAMEMAX\AppData\Local\Programs\Python\Python311\Lib\smtplib.py", line 1050, in __init__
        SMTP.__init__(self, host, port, local_hostname, timeout,
      File "C:\Users\GAMEMAX\AppData\Local\Programs\Python\Python311\Lib\smtplib.py", line 255, in __init__
        (code, msg) = self.connect(host, port)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\GAMEMAX\AppData\Local\Programs\Python\Python311\Lib\smtplib.py", line 341, in connect
        self.sock = self._get_socket(host, port, self.timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\GAMEMAX\AppData\Local\Programs\Python\Python311\Lib\smtplib.py", line 1056, in _get_socket
        new_socket = super()._get_socket(host, port, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\GAMEMAX\AppData\Local\Programs\Python\Python311\Lib\smtplib.py", line 312, in _get_socket
        return socket.create_connection((host, port), timeout,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\GAMEMAX\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 851, in create_connection
        raise exceptions[0]
      File "C:\Users\GAMEMAX\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 836, in create_connection
        sock.connect(sa)

how can solve this?

**Comment by johnfelipe** [comment]
solve with app password in gmail accout
